export const ingredientOptions = [
  "Chicken breast",
  "Chicken thigh",
  "Beef mince",
  "Lamb mince",
  "Salmon fillet",
  "Tuna",
  "Prawns",
  "Eggs",
  "Tofu",

  "Milk",
  "Butter",
  "Cream",
  "Coconut cream",
  "Cheddar cheese",
  "Parmesan",
  "Greek yoghurt",
  "Sour cream",
  "Cream cheese",
  "Mozzarella",

  "Basmati rice",
  "Jasmine rice",
  "Pasta",
  "Spaghetti",
  "Flour",
  "Breadcrumbs",
  "Oats",
  "Quinoa",
  "Couscous",
  "Noodles",

  "Onion",
  "Garlic",
  "Tomato",
  "Potato",
  "Sweet potato",
  "Carrot",
  "Broccoli",
  "Spinach",
  "Capsicum",
  "Zucchini",
  "Mushroom",
  "Corn",
  "Peas",
  "Celery",
  "Leek",

  "Olive oil",
  "Vegetable oil",
  "Coconut oil",
  "Soy sauce",
  "Fish sauce",
  "Tomato paste",
  "Canned tomatoes",
  "Chicken stock",
  "Vegetable stock",
  "Coconut milk",

  "Salt",
  "Pepper",
  "Cumin",
  "Paprika",
  "Turmeric",
  "Coriander",
  "Chilli flakes",
  "Cinnamon",
  "Oregano",
  "Thyme",
  "Basil",
  "Ginger",
  "Curry powder",
  "Garam masala",
  "Bay leaves",

  "Sugar",
  "Brown sugar",
  "Honey",
  "Baking powder",
  "Baking soda",
  "Vanilla extract",
  "Cocoa powder",
  "Dark chocolate",
  "Cornstarch",
  "Yeast",
].sort();

export const recipeOptions = [
  "Chicken curry",
  "Butter chicken",
  "Lamb curry",
  "Beef curry",
  "Prawn curry",
  "Chickpea curry",
  "Vegetable curry",
  "Lentil curry",
  "Fish curry",
  "Tofu curry",
  "Lamb tagine",
  "Lamb korma",
  "Chicken tikka masala",
  "Saag paneer",
  "Dal makhani",
  "Pasta bolognese",
  "Spaghetti carbonara",
  "Penne arrabiata",
  "Pasta primavera",
  "Mushroom risotto",
  "Seafood risotto",
  "Chicken risotto",
  "Vegetable fried rice",
  "Prawn fried rice",
  "Chicken fried rice",
  "Egg fried rice",
  "Biryani",
  "Vegetable soup",
  "Tomato soup",
  "Lentil soup",
  "Chicken soup",
  "Beef stew",
  "Lamb stew",
  "Minestrone",
  "French onion soup",
  "Pumpkin soup",
  "Pea soup",
  "Greek salad",
  "Caesar salad",
  "Caprese salad",
  "Nicoise salad",
  "Quinoa salad",
  "Salmon teriyaki",
  "Beef stir fry",
  "Vegetable stir fry",
  "Pad thai",
  "Chicken ramen",
  "Beef noodles",
  "Dumplings",
  "Spring rolls",
  "Sushi bowl",
  "Beef burger",
  "Chicken burger",
  "Fish tacos",
  "Margherita pizza",
  "BBQ pizza",
  "Grilled salmon",
  "Roast chicken",
  "Shepherd's pie",
  "Beef lasagne",
  "Quiche",
  "Pancakes",
  "French toast",
  "Omelette",
  "Scrambled eggs",
  "Avocado toast",
  "Banana bread",
  "Granola",
  "Smoothie bowl",

  "Chocolate cake",
  "Banana bread",
  "Cheesecake",
  "Brownies",
  "Cookies",
  "Apple crumble",
  "Tiramisu",
  "Panna cotta",
].sort();
